DEFAULT_CONFIGURATION_FILE = "./website_scraper_python.ini"

DEFAULT_MYSQL_HOST_NAME = "127.0.0.1"
DEFAULT_MYSQL_PORT_NUMBER = "3306"
DEFAULT_MYSQL_CHARSET = "utf8mb4"
DEFAULT_MYSQL_STORAGE_ENGINE_NAME = "InnoDB"
DEFAULT_MYSQL_CHARACTER_SET_NAME = "utf8mb4"
DEFAULT_MYSQL_COLLATION_NAME = "utf8mb4_unicode_ci"
